spring.application.name=dosebuddy

jwt.secret=zZ/LAIQZUNKt48SKqV7/uuXNrBfouK5H7YiKttl0LyY=

spring.ai.vertex.ai.gemini.project-id=dosebuddy-project
spring.ai.vertex.ai.gemini.location=us-central1

spring.ai.google.genai.api-key=${GOOGLE_API_KEY:}

spring.ai.vectorstore.pinecone.api-key=${PINECONE_API_KEY:}
spring.ai.vectorstore.pinecone.index-name=ai-rag-documents
spring.ai.vectorstore.pinecone.namespace=default